[package]
name = "json-tools"
version = "0.1.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
license = "MIT"
description = "A collections of tools to handle json encoded data"
repository = "https://github.com/Byron/json-tools"
keywords = ["json", "tools", "lexer"]
documentation = "http://byron.github.io/json-tools"
